### ISSUE TITLE
s1l3nt - SUPPORT_ROLE is never assigned, loss of funds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#10]
s1l3nt

high

# SUPPORT_ROLE is never assigned, loss of funds

## Summary
The role `SUPPORT_ROLE` is declared on the CouncilMember and StakingRewardsManager contracts but is never assigned to any address. This will lead to loss of funds because the operations to rescue ERC20 tokens will not work.

### CouncilMember.sol
```solidity
/* ========== ROLES ========== */
    // Role assigned for the governance council
    bytes32 public constant GOVERNANCE_COUNCIL_ROLE =
        keccak256("GOVERNANCE_COUNCIL_ROLE");
    // Support role for additional functionality
    bytes32 public constant SUPPORT_ROLE = keccak256("SUPPORT_ROLE");

 /************************************************
     *   helper functions
     ************************************************/

    /**
     * @notice Rescues any ERC20 token sent accidentally to the contract
     * @dev Only addresses with the SUPPORT_ROLE can call this function.
     * @param token ERC20 token address which needs to be rescued.
     * @param destination Address where the tokens will be sent.
     * @param amount Amount of tokens to be transferred.
     */
    function erc20Rescue(
        IERC20 token,
        address destination,
        uint256 amount
    ) external onlyRole(SUPPORT_ROLE) {                           // [x]
        token.safeTransfer(destination, amount);
    }
```

### StakingRewardsManager.sol
```solidity

    [...]
    bytes32 public constant SUPPORT_ROLE = keccak256("SUPPORT_ROLE");   //[x]
    [...]

    /// @notice Recover ERC20 tokens from THIS contract
    /// @param tokenAddress Address of the ERC20 token contract
    /// @param tokenAmount Amount of tokens to recover
    /// @param to The account to send the recovered tokens to
    function recoverERC20(
        IERC20 tokenAddress,
        uint256 tokenAmount,
        address to
    ) external onlyRole(SUPPORT_ROLE) {       // [x]
        //move funds
        tokenAddress.safeTransfer(to, tokenAmount);
    }
```
By cross referencing `SUPPORT_ROLE` we can see that it is used on certain rescue functions but is never called/intialized with `_grantRole(..)`.

## Impact
Loss of funds because does not exist any address with such role granted.

## Code Snippet

https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/sablier/core/CouncilMember.sol#L53

https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/telx/core/StakingRewardsManager.sol#L24

## Tool used

Manual Review

## Recommendation
Use `_grantRole(...)` to assert an address with SUPPORT_ROLE. This role is not even being used by the Council Members nor the Governance Council.

**Comment by nevillehuang** [comment]
Invalid, this can be granted by admin via `AccessControlUpgradeable.grantRole()` [here](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/access/AccessControlUpgradeable.sol#L143-L145) inherited by `CouncilMember.sol`
