### ISSUE TITLE
zzykxx - The `removeStakingRewardsContract()` and `topUp()` functions might interfere with each other leading to wrong top-ups

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#102]
zzykxx

medium

# The `removeStakingRewardsContract()` and `topUp()` functions might interfere with each other leading to wrong top-ups

## Summary

In `StakingRewardsManager.sol` the `removeStakingRewardsContract()` and `topUp()` functions might interfere with each other leading to wrong top-ups.

## Vulnerability Detail

There are two things to consider:
1. The `topUp(,uint256[] memory indices)` function takes as input an array of indices to specify which staking rewards contracts to top up.
2. The `removeStakingRewardsContract()` swaps the indices of the staking rewards contracts around, this is done to remove an array element in O(1) time.

If a `removeStakingRewardsContract()` and a `topUp()` transactions are sent and `removeStakingRewardsContract()` is executed before `topUp()` the staking reward contracts that will be topped could be the wrong ones.

This might happen:
- **Accidentally:** The functions are executed around the same time because the admins (`BUILDER_ROLE`, `EXECUTOR_ROLE`) are unaware of this issue, or the network is congested.
- **Purposefully:** The `BUILDER_ROLE` admin front runs the `EXECUTOR_ROLE` admin with calls that swap around the staking contracts indexes to his advantage.

## Impact
Top-ups might be executed on the wrong staking rewards contracts.

## Code Snippet
- [removeStakingRewardsContract()](https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/telx/core/StakingRewardsManager.sol#L166-L179)
- [topUp()](https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/telx/core/StakingRewardsManager.sol#L254-L278)
## Tool used

Manual Review

## Recommendation

Change the `topUp()` function to take as input an array of addresses of the staking reward contracts to top-up.

**Comment by nevillehuang** [comment]
Invalid, these functions are admin gated functions so they are trusted to make this error
