### ISSUE TITLE
araj - Use if-revert instead of require statement to save gas

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-01-telcoin-judging#121]
araj

medium

# Use if-revert instead of require statement to save gas

## Summary
Use if-revert instead of require statement to save gas in all the functions for checks

## Vulnerability Detail
If-revert is more gas efficient than require statement, protocol is heavily using require statement for checks, some examples are
```solidity
 require(
            address(telcoin) != address(0) &&
                address(council) != address(0) &&
                period != 0,
            "TelcoinDistributor: cannot intialize to zero"
        );
```

## Impact
If-revert will increase gas efficiency

## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/protocol/core/TelcoinDistributor.sol#L61C9-L66C11

## Tool used
Manual Review

## Recommendation
Use If-revert
```diff
+  if(condition){
+        revert custom__error
+   }
```

**Comment by nevillehuang** [comment]
Invalid, gas optimization findings are not valid based on sherlock rules
