### ISSUE TITLE
bigbick123456789000 - Risk of transaction revert in `batchTelcoin` function since the contract doesn't approve spending of Telcoin tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#148]
bigbick123456789000

medium

# Risk of transaction revert in `batchTelcoin` function since the contract doesn't approve spending of Telcoin tokens

## Summary
The `batchTelcoin` function in the `TelcoinDistributor` contract lacks an explicit check for token approval before attempting to transfer Telcoin tokens. This may lead to unexpected behavior if the contract has not been approved to spend the required Telcoin amount. This issue can result in transaction reverts and potential disruptions in the intended workflow.
## Vulnerability Detail
The `batchTelcoin` function is designed to transfer Telcoin tokens in batches to specified destinations. However, it assumes that the contract has been pre-approved to spend the necessary amount of Telcoin. Without an explicit check for approval, if the contract lacks the required allowance, the `safeTransferFrom` operation will fail, resulting in a transaction revert.
```solidity
function batchTelcoin(
    uint256 totalWithdrawal,
    address[] memory destinations,
    uint256[] memory amounts
) internal {
    // ... (omitted for brevity)

    // transfers amounts
    TELCOIN.safeTransferFrom(owner(), address(this), totalWithdrawal);

    // ... (omitted for brevity)

    // Balance Check
    require(
        TELCOIN.balanceOf(address(this)) == initialBalance,
        "TelcoinDistributor: must not have leftovers"
    );
}

```
## Impact
The `batchTelcoin` function may consistently revert, potentially leading to a Denial-of-Service (DoS) scenario. This situation arises when the contract lacks explicit checks for token approval, causing the `safeTransferFrom` operation to fail due to insufficient allowances. As a result, any attempt to execute the `batchTelcoin` function without proper approval may consistently result in transaction reverts, leading to a DoS condition where the intended functionality of the contract is disrupted.
## Code Snippet
[Link](https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/protocol/core/TelcoinDistributor.sol#L185-L203)
## Tool used

Manual Review

## Recommendation
Introduce an explicit approval check within the `batchTelcoin` function. This check ensures that the contract has the necessary allowance to spend Telcoin tokens before attempting transfers.

**Comment by nevillehuang** [comment]
Invalid, `batchTelcoin()` is only called within `executeTransaction()`, wherein approval will have been supplied externally by owner
