### ISSUE TITLE
BAICE - Missing return value in`SafeGuard:checkTransaction`, cannot check whether this transaction has been Vetoed

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#174]
BAICE

medium

# Missing return value in`SafeGuard:checkTransaction`, cannot check whether this transaction has been Vetoed

## Summary
No return value in `SafeGuard:checkTransaction`, cannot check whether this transaction has been vetoed.

## Vulnerability Detail
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/zodiac/core/SafeGuard.sol#L48-L75

This checkTransaction method check whether this transactionHash list (calculated by transaction params ) has been vetoed, no return value .

## Impact
This function of `checkTransaction` will not work ， and will influence other function results based on this `checkTransaction` method .

## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/zodiac/core/SafeGuard.sol#L48-L75

```solidity
function checkTransaction(
        address to,
        uint256 value,
        bytes memory data,
        Enum.Operation operation,
        uint256,
        uint256,
        uint256,
        address,
        address payable,
        bytes memory,
        address
    ) external view override {
        // cycles through possible transactions
        for (uint256 i = 0; i < nonces.length; i++) {
            bytes32 transactionHash = IReality(_msgSender()).getTransactionHash(
                to,
                value,
                data,
                operation,
                nonces[i]
            );
            require(
                !transactionHashes[transactionHash],
                "SafeGuard: transaction has been vetoed"
            );
        }
    }
```

## Tool used

Manual Review VSCode

## Recommendation
Add boolean return value 
```solidity
function checkTransaction(
        address to,
        uint256 value,
        bytes memory data,
        Enum.Operation operation,
        uint256,
        uint256,
        uint256,
        address,
        address payable,
        bytes memory,
        address
@-    ) external view override  {
@+    ) external view override returns (bool) {
    ---
return true ;
```

**Comment by nevillehuang** [comment]
Invalid, [check done here](https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/zodiac/core/SafeGuard.sol#L70-L75), explicit return value is not required
