### ISSUE TITLE
BAICE - `SafeGuard` contract is not inherited from pre-written `IGuard` interface,

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#176]
BAICE

medium

# `SafeGuard` contract is not inherited from pre-written `IGuard` interface,

## Summary
The `SafeGuard ` contract is not inherited from `IGuard` contract .

## Vulnerability Detail
The `SafeGuard ` contract is inherited from `BaseGuard` and `Ownable` contract, and the `BaseGuard` is inherited from `IERC165`contract , so `SafeGuard` contract is no relation to `IGuard` contract .
`contract SafeGuard is BaseGuard, Ownable {`
`abstract contract BaseGuard is IERC165 {`

## Impact
`IGuard` contract is useless , but `BaseGuard` write two `IGuard` methods .
` function checkTransaction(`
` function checkAfterExecution(bytes32, bool) external view override {}`

but `checkAfterExecution` function is not used here .

## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/zodiac/core/SafeGuard.sol#L77-L78

```solidity
  // not used
    function checkAfterExecution(bytes32, bool) external view override {}
```

```solidity
    function checkAfterExecution(bytes32 txHash, bool success) external virtual;
```

## Tool used

Manual Review, VSCode

## Recommendation
The `BaseGuard` contract should implement `IGuard` interface, or , both `SafeGuard` and `BaseGuard` should delete unused `checkAfterExecution` function .

**Comment by nevillehuang** [comment]
Invalid, this is at most a gas optimization finding not valid based on sherlock rules
