### ISSUE TITLE
ubl4nk - Risk of locked assets due to use of _mint instead of _safeMint

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#22]
ubl4nk

high

# Risk of locked assets due to use of _mint instead of _safeMint

## Summary
ERC-721 tokens are minted via the _mint function rather than the _safeMint function.
Due to that a councilMember can be contract, the `_safeMint` should be used.

## Vulnerability Detail
The _safeMint function includes a necessary safety check that validates a recipient contract’s ability to receive and handle ERC-721 tokens.
Without this safeguard, tokens can inadvertently be sent to an incompatible contract, causing them, and any assets they hold, to become irretrievable:
```solidity
function mint(
        address newMember
    ) external onlyRole(GOVERNANCE_COUNCIL_ROLE) {
        if (totalSupply() != 0) {
            _retrieve();
        }

        balances.push(0);
        _mint(newMember, totalSupply());
    }
```
## Impact
If councilMember contract is unable to receive ERC721 tokens (doesn't support onERC721Received), the NFT asset will be lost.
## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/0954297f4fefac82d45a79c73f3a4b8eb25f10e9/telcoin-audit/contracts/sablier/core/CouncilMember.sol#L181
## Tool used

Manual Review

## Recommendation
Use the _safeMint function instead of _mint.

**Comment by nevillehuang** [comment]
Invalid based on sherlock rules
