### ISSUE TITLE
iberry - The _withdrawAll function in the CouncilMember contract does not adhere to the CEI pattern

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#223]
iberry

medium

# The _withdrawAll function in the CouncilMember contract does not adhere to the CEI pattern

## Summary
_withdrawAll function does not adhere to the CEI pattern
## Vulnerability Detail
The _withdrawAll function in the CouncilMember，first call transfer money，then set balances[tokenId] = 0;this may  be cause reentry。
## Impact
medium，may be lead to reentry
## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/sablier/core/CouncilMember.sol#L339-L341
## Tool used

Manual Review

## Recommendation
    function _withdrawAll(address from, uint256 tokenId) internal {
        uint256 amount =  balances[tokenId];
         balances[tokenId] = 0;
        TELCOIN.safeTransfer(from, amount);
        
    }

**Comment by nevillehuang** [comment]
Invalid, insufficient proof that reentrancy is possible.
