### ISSUE TITLE
0xlucky - StakingRewards: Significant loss of precision possible

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#253]
0xlucky

medium

# StakingRewards: Significant loss of precision possible

## Vulnerability Detail

In notifyRewardAmount, the reward rate per second is calculated. This calculation rounds down, which can lead to situations where significantly less rewards are paid out to stakers, because the effect of the rounding is multiplied by the duration.

## Impact
Let's say we have a rewardsDuration of 4 years, i.e. 126144000 seconds. We assume the rewardRate is currently ß and notifyRewardAmount is called with the reward amount 252287999. Because the calculation rounds down, rewardRate will be 1. After the 4 years, the user have received 126144000 reward tokens. However, 126143999 (i.e., almost 50%) of the reward tokens that were intended to be distributed to the stakers were not distributed, resulting in monetary loss for all stakers.

 if we consider small token decimals (eg. EURS with 2 decimals).
## Code Snippet

https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/telx/core/StakingRewardsManager.sol#L274
## Tool used

Manual Review

## Recommendation
You could accumulate the differences that occur due to rounding and let the users claim them in the end according to their shares.

**Comment by nevillehuang** [comment]
Low severity , reward tokens will be supplied by admins directly via `topUp`, so the arbitrary `252287999` is speculating on admin configuration.
