### ISSUE TITLE
0x_Sanzcy - `removeFromOffice` doesn't check if `to` is already a council member

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#28]
0x_Sanzcy

medium

# `removeFromOffice` doesn't check if `to` is already a council member

## Summary
When a council member becomes malicious or for some other reasons the `GOVERNANCE_COUNCIL_ROLE` will call `removeFromOffice `  swapping the council member with a new council member 
```solidity
function removeFromOffice(
        address from,
        address to,
        uint256 tokenId,
        address rewardRecipient
    ) external onlyRole(GOVERNANCE_COUNCIL_ROLE) {
        // Retrieve and distribute any pending TELCOIN for all council members
        _retrieve();
        // Withdraw all the TELCOIN rewards for the specified token to the rewardRecipient
        _withdrawAll(rewardRecipient, tokenId);
        // Transfer the token (representing the council membership) from one address to another
        _transfer(from, to, tokenId);
    }
```

## Vulnerability Detail
If the new council member `to` is already a council member they'll posses multiple `tokenId` representing their council membership this can have the following impacts;
1- if the council member becomes malicious removing such member will result in only removing one `tokenId` associated with the member, the council member will still be present in the system due to holding other `tokenId `

2- unfair reward distribution, whenever `_retrive` gets called the user will earn for all the `tokenId` held 
## Impact
Membership will become harder to track 
## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit%2Fcontracts%2Fsablier%2Fcore%2FCouncilMember.sol#L122-L134
## Tool used

Manual Review

## Recommendation
Include a check if `to` is already a council member

**Comment by nevillehuang** [comment]
Invalid, this will constitute admin input error not valid based on sherlock rules see point 5.
