### ISSUE TITLE
krkba - `claim()` function does not check if the amount is greater than zero.

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-01-telcoin-judging#3]
krkba

high

# `claim()` function does not check if the amount is greater than zero.

krkba
## Vulnerability Detail
If the function does not check whether the claimed amount is greater than zero, it can have potentially impact on the  contract security.
## Impact
Without check for a positive amount, caller might be able to claim rewards with an amount of zero or even a negative value.
## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/sablier/core/CouncilMember.sol#L92-L111
## Tool used

Manual Review

## Recommendation
include a validation check in the `claim` function to ensure that the claimed amount is greater than zero.

**Comment by nevillehuang** [comment]
Invalid, [check](https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/sablier/core/CouncilMember.sol#L102-L105) here is sufficient.
