### ISSUE TITLE
krkba - No zero address validation in `setRewardsDistribution` function

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#4]
krkba

medium

# No zero address validation in `setRewardsDistribution` function

krkba
## Vulnerability Detail
The `setRewardsDistribution` function does not validate the input address. 
## Impact
It can be a zero address, which leads to unexpected behavior.
## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/telx/abstract/RewardsDistributionRecipient.sol#L42-L47
## Tool used

Manual Review

## Recommendation
The function should check that the address is not the zero address.

**Comment by amshirif** [comment]
https://github.com/telcoin/telcoin-audit/compare/fix-review...4-no-zero-address-validation-in-setrewardsdistribution?expand=1

**Comment by amshirif** [comment]
https://github.com/telcoin/telcoin-audit/pull/21

**Comment by krkbaa** [comment]
I can't get in to this reference link,can you tell what is is it please.

**Comment by nevillehuang** [comment]
Invalid, address zero checks are not valid based on sherlock rules

**Comment by sherlock-admin** [comment]
The protocol team fixed this issue in PR/commit https://github.com/telcoin/telcoin-audit/pull/21.

**Comment by sherlock-admin** [comment]
The Lead Senior Watson signed-off on the fix.
