### ISSUE TITLE
iberry - Don't _grantRole many "XXX_ROLE" within the initialize function of the StakingRewardsManager

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#48]
iberry

high

# Don't _grantRole many "XXX_ROLE" within the initialize function of the StakingRewardsManager

## Summary
because XXX_ROLE variable don't init, onlyRole modifier function will disable.
 
## Vulnerability Detail
Some constants, denoted as "XXX_ROLE,"  (BUILDER_ROLE etc) are not being properly set up within the initialize function. Consequently, when the onlyRole(onlyRole(MAINTAINER_ROLE) modifier is applied, the verification fails. This issue is impacting the functionality of the contract

## Impact
high
## Code Snippet

https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/telx/core/StakingRewardsManager.sol#L22-L26

https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/telx/core/StakingRewardsManager.sol#L69-L85

## Tool used

Manual Review

## Recommendation
add _grantRole function at initialize function.
_grantRole(XXX_ROLE, _msgSender());

**Comment by nevillehuang** [comment]
Invalid, this roles can be granted by admin via `AccessControlUpgradeable.grantRole()` [here](https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/access/AccessControlUpgradeable.sol#L143-L145) inherited by `StakingRewardsManager.sol`
