### ISSUE TITLE
bareli - creation or loss of tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#50]
bareli

medium

# creation or loss of tokens

## Summary
The batchTelcoin function requires the contract to have a balance equal to the initial balance after transfers, which prevents the creation or loss of tokens. However, this check could be problematic if there are any unrelated token transfers to the contract, as it would prevent the execution of any transactions.

## Vulnerability Detail
 uint256 initialBalance = TELCOIN.balanceOf(address(this));
        //transfers amounts
        TELCOIN.safeTransferFrom(owner(), address(this), totalWithdrawl);
        for (uint i = 0; i < destinations.length; i++) {
            TELCOIN.safeTransfer(destinations[i], amounts[i]);
        }
        //initial balance is used instead of zero
        //if 0 is used instead stray Telcoin could DNS operations
        require(
            TELCOIN.balanceOf(address(this)) == initialBalance,
            "TelcoinDistributor: must not have leftovers"
        );
    }
## Impact
 It would prevent the execution of any transactions.
## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/protocol/core/TelcoinDistributor.sol#L185
## Tool used

Manual Review

## Recommendation

Duplicate of #250

**Comment by amshirif** [comment]
The behavior of the Telcoin contract is own. There is no concurrency on the blockchain so there is no opportunity for Telcoin to be sent to the contract in-between the balance checks. The only way in which this would revert is if 1. The entire balance was not sent as it was supposed to or 2. One of the destinations was the address itself, which should never be the case.
