### ISSUE TITLE
bareli - Centralization Risks

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#58]
bareli

medium

# Centralization Risks

## Summary
Centralization Risks: The contract relies heavily on roles for management, which could lead to centralization if not distributed properly.

## Vulnerability Detail
  modifier OnlyAuthorized() {
        require(
            hasRole(GOVERNANCE_COUNCIL_ROLE, _msgSender()) ||
                ERC721Upgradeable.balanceOf(_msgSender()) >= 1,
            "CouncilMember: caller is not council member or owner"
        );
        _;
    }
## Impact
The contract relies heavily on roles for management, which could lead to centralization if not distributed properly.

## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/sablier/core/CouncilMember.sol#L122
## Tool used

Manual Review

**Comment by nevillehuang** [comment]
Invalid, admins are trusted entities
