### ISSUE TITLE
bareli - Centralization Risk:

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#60]
bareli

medium

# Centralization Risk:

## Summary
Centralization Risk: Since the contract relies on the Ownable pattern, there is a central point of control (the owner). If the owner's private key is compromised, the attacker could change the rewardsDistribution address to a malicious one.

## Vulnerability Detail
 function setRewardsDistribution(
        address rewardsDistribution_
    ) external onlyOwner {
        rewardsDistribution = rewardsDistribution_;
        emit RewardsDistributionUpdated(rewardsDistribution);
    }

## Impact
If the owner's private key is compromised, the attacker could change the rewardsDistribution address to a malicious one.
## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/telx/abstract/RewardsDistributionRecipient.sol#L42
## Tool used

Manual Review

**Comment by nevillehuang** [comment]
Invalid, admins are trusted entities and not malicious
