### ISSUE TITLE
bareli - Single Point of Failure:

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#62]
bareli

medium

# Single Point of Failure:

## Summary
Single Point of Failure: The contract assumes that the rewardsDistribution address is a trusted entity. If the contract at this address has vulnerabilities or is malicious, it could potentially disrupt the reward distribution process or lead to loss of funds.

## Vulnerability Detail
 function setRewardsDistribution(
        address rewardsDistribution_
    ) external onlyOwner {
        rewardsDistribution = rewardsDistribution_;
        emit RewardsDistributionUpdated(rewardsDistribution);
    }

## Impact
If the contract at this address has vulnerabilities or is malicious, it could potentially disrupt the reward distribution process or lead to loss of funds.
## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/telx/abstract/RewardsDistributionRecipient.sol#L42
## Tool used

Manual Review

**Comment by nevillehuang** [comment]
Invalid, admins are trusted entities and not malicious
