### ISSUE TITLE
bareli - Lack of Validation:

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#64]
bareli

medium

# Lack of Validation:

## Summary
Lack of Validation: When setting the rewardsDistribution address, there is no check to ensure that the address is a contract and not a regular externally owned account (EOA). This could lead to errors if an EOA is mistakenly set as the rewardsDistribution.

## Vulnerability Detail
 function setRewardsDistribution(
        address rewardsDistribution_
    ) external onlyOwner {
        rewardsDistribution = rewardsDistribution_;
        emit RewardsDistributionUpdated(rewardsDistribution);
    }

## Impact
there is no check to ensure that the address is a contract and not a regular externally owned account (EOA). This could lead to errors if an EOA is mistakenly set as the rewardsDistribution.

## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/telx/abstract/RewardsDistributionRecipient.sol#L42
## Tool used

Manual Review

**Comment by nevillehuang** [comment]
Invalid, this would constitute admin input error not valid based on sherlock rules see point 5.
