### ISSUE TITLE
bareli - Unused Implementation Address:

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#66]
bareli

medium

# Unused Implementation Address:

## Summary
Unused Implementation Address: The stakingRewardsImplementation is set but never used. This could be a leftover from a previous design where the factory might have been intended to use a proxy pattern for creating new StakingRewards contracts. If it's not needed, it should be removed to avoid confusion.

## Vulnerability Detail
   constructor(address implementation) Ownable(_msgSender()) {
        stakingRewardsImplementation = implementation;
    }
## Impact
This could be a leftover from a previous design where the factory might have been intended to use a proxy pattern for creating new StakingRewards contracts. If it's not needed, it should be removed to avoid confusion.
## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/telx/core/StakingRewardsFactory.sol#L32
## Tool used

Manual Review

## Recommendation
 If it's not needed, it should be removed to avoid confusion.

**Comment by nevillehuang** [comment]
Invalid, this is at most a gas optimization issue. My understanding is this address is set to allow users to utilize a public getter function to view the implementation contract of staking rewards.
