### ISSUE TITLE
bareli - Gas Optimization:

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#70]
bareli

medium

# Gas Optimization:

## Summary
Gas Optimization: The createStakingRewards function could be optimized by storing the length of the stakingRewardsContracts array in a local variable instead of calling getStakingRewardsContractCount() to save on gas costs.

## Vulnerability Detail
   emit NewStakingRewardsContract(
            getStakingRewardsContractCount() - 1,
            rewardsToken,
            stakingToken,
            StakingRewards(stakingRewards)
        );

        return StakingRewards(stakingRewards);
    }
## Impact
Gas Optimization:
## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/telx/core/StakingRewardsFactory.sol#L58
## Tool used

Manual Review

## Recommendation
The createStakingRewards function could be optimized by storing the length of the stakingRewardsContracts array in a local variable instead of calling getStakingRewardsContractCount() to save on gas costs.

**Comment by nevillehuang** [comment]
Invalid, gas optimization findings are not valid based on sherlock rules
