### ISSUE TITLE
mstpr-brainbot - StakingRewardsManager lacks pausing functionality control

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#78]
mstpr-brainbot

medium

# StakingRewardsManager lacks pausing functionality control

## Summary
StakingReward contracts inherits pause and the owner of these contracts are the StakingRewardsManager contract. However, manager contract has no functionality to trigger the pause function in rewards contracts.
## Vulnerability Detail
Staking rewards contracts inherit the Pausable functionality and include pausable functions.
https://github.com/sherlock-audit/2024-01-telcoin/blob/0954297f4fefac82d45a79c73f3a4b8eb25f10e9/telcoin-audit/contracts/telx/core/StakingRewards.sol#L139-L141

The owner of the staking rewards contracts is the manager contract. However, the manager contract lacks control over the pause functions in the staking rewards contract.
## Impact
StakingRewards contract is not in scope and the pausable external functions are not added in it. Tho, manager contract in scope and since the reward contract has pausable functions, manager contract should have the pausable functions to trigger them which it lacks it. I'd say this is a valid medium.
## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/0954297f4fefac82d45a79c73f3a4b8eb25f10e9/telcoin-audit/contracts/telx/core/StakingRewards.sol#L139-L141
## Tool used

Manual Review

## Recommendation
Add pause functions to both StakingRewards and StakingRewardsManager

**Comment by amshirif** [comment]
`StakingRewards` is outside the scope of this audit. The pausing functionality is not to be implemented, hence its absence from the Manager.

**Comment by nevillehuang** [comment]
Invalid, out of scope. Additionally, `StakingRewardsManager` do not require pausing.
