### ISSUE TITLE
bareli - Unused Parameters:

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#80]
bareli

medium

# Unused Parameters:

## Summary
Unused Parameters: The checkTransaction function has several parameters that are not used, which could indicate that the function is not fully implemented or that there is unnecessary complexity in the contract interface.

## Vulnerability Detail
 function checkTransaction(
        address to,
        uint256 value,
        bytes memory data,
        Enum.Operation operation,
        uint256,
        uint256,
        uint256,
        address,
        address payable,
        bytes memory,
        address
    ) external view override {
## Impact
The checkTransaction function has several parameters that are not used, which could indicate that the function is not fully implemented or that there is unnecessary complexity in the contract interface.

## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/zodiac/core/SafeGuard.sol#L48
## Tool used

Manual Review

**Comment by nevillehuang** [comment]
Invalid, this is at most a gas optimization finding not valid based on sherlock rules
