### ISSUE TITLE
0x_Sanzcy - RewardTokens will be lost if staking contract gets removed

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#82]
0x_Sanzcy

medium

# RewardTokens will be lost if staking contract gets removed

## Vulnerability Detail
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit%2Fcontracts%2Ftelx%2Fcore%2FStakingRewardsManager.sol#L216-L225

```solidity
 function recoverERC20FromStaking(
        StakingRewards staking,
        IERC20 tokenAddress,
        uint256 tokenAmount,
        address to
    ) external onlyRole(SUPPORT_ROLE) {
        // grab the tokens from the staking contract
        staking.recoverERC20(to, tokenAddress, tokenAmount);
    }
```
`recoverERC20FromStaking` only recovers the staking tokens which will be external  tokens and not the `rewardToken` if the staking contract gets removed the rewardToken will be lost.

Reward tokens are sent from the `owner ` to the staking contract when in need of top up

Reward tokens are `Telcoin` which stakers recieve as rewards 

```solidity    
    function topUp(
        address source,
        uint256[] memory indices
    ) external onlyRole(EXECUTOR_ROLE) {
        for (uint i = 0; i < indices.length; i++) {
            // get staking contract and config
            StakingRewards staking = stakingContracts[i];
            StakingConfig memory config = stakingConfigs[staking];

            // will revert if block.timestamp <= periodFinish
            staking.setRewardsDuration(config.rewardsDuration);

            // pull tokens from owner of this contract to fund the staking contract
            rewardToken.transferFrom(
                source,
                address(staking),
                config.rewardAmount
            );

            // start periods
            staking.notifyRewardAmount(config.rewardAmount);

            emit ToppedUp(staking, config);
```
If significant amount of rewards tokens was sent to the staking contracts they will all be lost 
## Tool used

Manual Review

## Recommendation
Include a logic to retrieve `rewardTokens`

**Comment by nevillehuang** [comment]
Invalid, this will introduce uncessary complexity. Any donated reward tokens is donators mistake and so could be distributed to stakers.
