### ISSUE TITLE
eeshenggoh - Lack of check if proxy executed was successful leading to inaccurate update of rewards

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2024-01-telcoin-judging#84]
eeshenggoh

high

# Lack of check if proxy executed was successful leading to inaccurate update of rewards

## Summary
`CouncilMember::_retrieve()` is used to retrieve and distribute TELCOIN to council members based on the stream from` _target`. It uses a Sabiler PRBproxy to withdraw tokens to the `CouncilMembers` contract. The problem lies in not checking whether the transaction is successful.

## Vulnerability Detail
The `CouncileMember.sol::retrieve()` calls the `IPRBProxy.sol::execute()` which performs a delegate call to withdraw tokens. In the [IPRBProxy.sol from Etherscan](https://etherscan.io/address/0x638a7aC8315767cEAfc57a6f5e3559454347C3f6#code#F7#L53) execute function's Natspec states that `It returns the data it gets back, and bubbles up any potential revert`. This means that, if the target contract's function being called through execute encounters a revert, that revert is not caught or handled within the execute function itself. Instead, it is allowed to propagate back to the caller of the execute function, and the caller can decide how to handle or react to the revert. 

## Impact
The retrieval and distribution of TELCOIN will be inaccurate hence, causing users to lose their TELCOIN rewards.
## Code Snippet
https://github.com/sherlock-audit/2024-01-telcoin/blob/main/telcoin-audit/contracts/sablier/core/CouncilMember.sol#L270-L279
## Tool used

Manual Review

## Recommendation
1) Handle the `(bytes memory response)` received 
```solidity
bytes memory response = _stream.execute(
    _target,
    abi.encodeWithSelector(
        ISablierV2ProxyTarget.withdrawMax.selector,
        _target,
        _id,
        address(this)
    )
);
// Custom Error helps saves gas
error ExecuteFail();

// Check if the response indicates a revert
if (response.length > 0) {
    // Handle revert
    // You may parse the response to get the revert reason
    // Note: The exact method depends on the implementation of your contracts
    revert ExecuteFail();
}

```

**Comment by amshirif** [comment]
https://github.com/telcoin/telcoin-audit/pull/37

**Comment by 0xLogos** [comment]
@amshirif @goheesheng Assuming call can silently fail without revert. Exactly where and which funds are lost? How propesed solution helps?

**Comment by 0xLogos** [comment]
Escalate 
Invalid
Proposed solution (reverting) doesn't make any difference

**Comment by sherlock-admin** [comment]
> Escalate 
> Invalid
> Proposed solution (reverting) doesn't make any difference

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xf1b0** [comment]
I agree with the escalation. The proposed solution doesn't make any difference, as the call already reverts.
Furthermore, it's exactly what we don't want, as it results in a DoS, as described in  #139 and #47.

**Comment by goheesheng** [comment]
Silent reverts can be variant of a DoS but it will return a value which can be checked via the if statement

**Comment by goheesheng** [comment]
> I agree with the escalation. The proposed solution doesn't make any difference, as the call already reverts.
> Furthermore, it's exactly what we don't want, as it results in a DoS, as described in  #139 and #47.

Also using the #139 is using stream directly and hence changing the address. But there isn't a check for the returned value, hence it's clearly non duplicate of #139.

**Comment by goheesheng** [comment]
> I agree with the escalation. The proposed solution doesn't make any difference, as the call already reverts.
> Furthermore, it's exactly what we don't want, as it results in a DoS, as described in  #139 and #47.

Also using the #139is using stream directly and hence changing the address. But there isn't a check for the returned value, hence it's clearly non duplicate of #139.

**Comment by 0xArz** [comment]
This is clearly not a valid issue as the `_execute()` checks if the delegatecall was succesful or no, see here:

https://etherscan.io/address/0x584009E9eDe26e212182c9745F5c000191296a78#code#F5#L123
https://github.com/PaulRBerg/prb-proxy/blob/fa13cf09fbf544a2d575b45884b8e94a79a02c06/src/PRBProxy.sol#L69-L79


```solidity
if (!success) {
            // If there is return data, the delegate call reverted with a reason or a custom error, which we bubble up.
            if (response.length > 0) {
                assembly {
                    // The length of the data is at `response`, while the actual data is at `response + 32`.
                    let returndata_size := mload(response)
                    revert(add(response, 32), returndata_size)
                }
            } else {
                revert PRBProxy_ExecutionReverted();
            }
        }

```
And the execution will revert here and it doesnt matter what data it returns,  if there really was a silent revert then it would be a problem in the PRBProxy not in the telcoin contracts.  

PRBProxy.execute() is not called with .call() so we dont need to check the return value because execution will revert there and the transaction will fail

**Comment by amshirif** [comment]
I agree with the escalation.

**Comment by nevillehuang** [comment]
In that case this issue should be invalid.

**Comment by Evert0x** [comment]
Planning to accept escalation and invalidate issue

**Comment by Evert0x** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xLogos](https://github.com/sherlock-audit/2024-01-telcoin-judging/issues/84/#issuecomment-1916898878): accepted

**Comment by sherlock-admin** [comment]
The protocol team fixed this issue in PR/commit https://github.com/telcoin/telcoin-audit/pull/37.

**Comment by sherlock-admin** [comment]
The Lead Senior Watson signed-off on the fix.
